import type { Metadata } from "next";
import { Space_Grotesk, Bai_Jamjuree } from "next/font/google";

import "./globals.css";
import AppNavbar from "@/components/AppNavbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

const baiJamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-bai-jamjuree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${baiJamjuree?.variable} antialiased`}
      >
        <AppNavbar />
        {children}
      </body>
    </html>
  );
}
